name: Code Review by GPT-4

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Poetry virtual environment
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install Dependencies
        run: poetry install

      - name: Run Flake8 Linting
        run: poetry run flake8 .

      - name: Run Mypy Type Check
        run: poetry run mypy .

      - name: Run Bandit Security Check
        run: poetry run bandit -r .

      - name: Get Changed Hunks
        run: |
          # ... (existing code for getting diffs)

      - name: Code Review with GPT-4
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          poetry run python review_with_gpt4.py

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            "Code Review Results:\n\n${{ steps.review.outputs.results }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Flake8 Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake8-report.txt
